# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-18 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_tag_etc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='wallet1',
        ),
        migrations.AddField(
            model_name='goal',
            name='wallet12',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.PROTECT, to='wallet_tag_etc.Wallet', verbose_name='Wallet2'),
            preserve_default=False,
        ),
    ]
