# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-25 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transfer_related',
            field=models.OneToOneField(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.Transaction'),
        ),
    ]
